version: "1"
services:
  CommunityService:
    container_name: CommunityService
    image: communityService:local-test
    build: .
    ports:
      - "15001:15001"
    environment:
      PORT: 15001
      MESSAGEQ_URL: amqp://guest:guest@0.0.0.0:5672
      SQL_DB_URI: postgres://postgres:postgres@0.0.0.0:32768/postgres